formats:
  current_date_time_format: '%b %d, %Y'
displays:
  should_display_image: true
  should_display_blocks: true
  should_display_text: true
alignments:
  space_before: 2
  space_after: 2
  lines_before: 2
  lines_after: 2
  hr_node_repeat: 18
  word_wrap: 30
  color_block_padding: 4
chars:
  hr_divider_node: 8729
  default_bullet: 8729
  sys_distro_bullet: 64306
  sys_shell_bullet: 62601
  current_date_time_bullet: 61555
colors:
  default_text_color: Black
  username_color: Green
  device_name_color: Yellow
  welcome_message_color: LightGreen
  hr_color: LightBlue
  default_bullet_color: LightBlue
  sys_distro_bullet_color: LightRed
  sys_shell_bullet_color: LightMagenta
  current_date_time_bullet_color: LightCyan
overrides:
  username_override: null
  device_name_override: null
  sys_distro_override: null
  sys_shell_override: null
details:
  welcome_message: Hello, this is a sample message. Have a good day!
